version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
clone_depth: 1
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    $version=$([regex]"(?i)AssemblyFileVersion\(`"(.*?)`"\)").matches($(gc .\src\GlavoUI\Properties\AssemblyInfo.cs)).Groups[1].Value
    sc .\src\GlavoUI\GlavoUI.nuspec $(gc  .\src\GlavoUI\GlavoUI.nuspec).replace('$version$',$version)
build:
  publish_nuget: true
  verbosity: minimal