#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GlavoUI.Resource", IsApplication=false)]

namespace GlavoUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int glavo_audio_button_recording = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int glavo_audio_button_recordnormal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int glavo_audio_cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int glavo_audio_dialog_loading_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int glavo_audio_recorder = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int glavo_audio_v1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int glavo_audio_v2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int glavo_audio_v3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int glavo_audio_v4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int glavo_audio_v5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int glavo_audio_v6 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int glavo_audio_v7 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int glavo_audio_voice_too_short = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int GlavoAudioButtonDialogManager_Icon = 2131099648;
			
			// aapt resource value: 0x7f060002
			public static int GlavoAudioButtonDialogManager_Text = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int GlavoAudioButtonDialogManager_Voice = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int GlavoAudioButtonDialogManager = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int GlavoAudioRecordButtonNormal = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int GlavoAudioRecordButtonRecording = 2130968577;
			
			// aapt resource value: 0x7f040004
			public static int GlavoAudioRecordButtonTooShort = 2130968580;
			
			// aapt resource value: 0x7f040003
			public static int GlavoAudioRecordButtonUpToCancel = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int GlavoAudioRecordButtonWantToCancel = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public static int Theme_audioDialog = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
